### ISSUE TITLE
Wrong Elo being displayed

### ISSUE THREAD

**Issue by Luecx** [truekendor/better-ccc-extension#7]
I noticed this a few times now where the elo displayed is incorrect. An example would be:

![grafik](https://github.com/truekendor/better-ccc-extension/assets/34272583/5c4877d2-daac-4d57-b4ea-e36a5c68f6c9)

I have already cleared the cache and have automatic updates enabled. Is this a known problem?

Version: 1.1.6 

Otherwise great extension! :)

**Comment by truekendor** [comment]
Hey, thanks for the bug report

Clearing cache won't help, problem
definitely in the code

This bug occurs randomly in
Firefox, especially Nightly & Nightly for android,
and I'm not sure why.
